{
 "title": "helloservice",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kubernetes_namespace)"
   },
   { "name": "app", "label": "app", "query": "label_values(app)" },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values({kubernetes_namespace=\"$namespace\",app=\"$app\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Camel Routes Completed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "org_apache_camel_ExchangesCompleted{context=\"helloservice\",type=\"routes\",kubernetes_namespace=\"$namespace\",app=\"$app\",instance=\"$instance\"}",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{kubernetes_namespace=\"$namespace\",app=\"$app\",instance=\"$instance\"}",
     "legendFormat": "{{area}}"
    }
   ]
  },
  {
   "title": "Camel exchange failures",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(org_apache_camel_ExchangesFailed{kubernetes_namespace=\"$namespace\",app=\"$app\",instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Camel processing time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "[ms]" }
   ],
   "targets": [
    {
     "expr": "org_apache_camel_LastProcessingTime{type=\"routes\",kubernetes_namespace=\"$namespace\",app=\"$app\",instance=\"$instance\"}>0",
     "legendFormat": "{{route}}"
    }
   ]
  }
 ]
}